In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
import os
os.getcwd()

'/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio'

In [3]:
# os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/MyDrive/kaggle'

In [4]:
# !pip install kaggle

In [5]:
# os.chdir('/content/drive/MyDrive/gdrive')

In [6]:
# !kaggle datasets download -d sripaadsrinivasan/audio-mnist

In [7]:
os.listdir()

['Detecting_phno_from_voice-20231013T045341Z-001.zip',
 'Detecting_PhoneNo_from_live_audio.ipynb',
 'Detecting_phno_from_voice',
 '.ipynb_checkpoints']

In [8]:
# import os
# os.makedirs(f'/content/drive/MyDrive/gdrive/Detecting_phno_from_voice',exist_ok=True)
# os.makedirs(f'/content/drive/MyDrive/gdrive/voice_data',exist_ok=True)

In [9]:
# zip_path = '/content/drive/MyDrive/gdrive/audio-mnist.zip'

In [10]:
# !cp {'zip_path'  '/content/drive/MyDrive/gdrive/voice_data'}

In [11]:
# !unzip -q 'audio-mnist.zip'

In [12]:
# import os
# os.chdir('/content/drive/MyDrive/gdrive/Detecting_phno_from_voice')

In [13]:
# voicedata = os.listdir('/content/drive/MyDrive/gdrive/data')

In [14]:
voicedata = os.listdir('/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice')

In [15]:
voicedata

['9', '0', '7', '6', '1', '8', '4', '3', '2', '5']

In [16]:
# voicedata.remove('audioMNIST_meta.txt')

In [17]:
# for i in range(0,10):
#   os.makedirs(os.path.join('/content/drive/MyDrive/gdrive/Detecting_phno_from_voice/',f'{i}'),exist_ok=True)

In [18]:
# import shutil

# for dir in voicedata:
#   for i in range(0, 10):
#     for j in range(0, 50):
#       src_path = os.path.join('/content/drive/MyDrive/gdrive/data', dir,f'{i}_{dir}_{j}.wav')
#       # print(src_path)
#       dst_path = os.path.join(f'/content/drive/MyDrive/gdrive/Detecting_phno_from_voice/', str(i))
#       # print(dst_path)
#       shutil.copy(src_path, dst_path)

In [19]:
def count_files_in_directory(path):
    total_files = 0

    for root, dirs, files in os.walk(path):
        total_files += len(files)

    return total_files

# Example usage:
directory_path = '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/'
total_files = count_files_in_directory(directory_path)
print(f"Total files in {directory_path}: {total_files}")


Total files in /Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/: 30000


In [20]:
# !pip install --upgrade tensorflow-io

In [21]:
import tensorflow_io as tfio
print(tfio.__version__)

0.34.0


/Users/pranav/anaconda3/envs/myenv/lib/python3.11/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/Users/pranav/anaconda3/envs/myenv/lib/python3.11/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/Users/pranav/anaconda3/envs/myenv/lib/python3.11/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/Users/pranav/anaconda3/envs/myenv/lib/python3.11/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/Users/pranav/anaconda3/envs/myenv/lib/python3.11/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ["dlopen(/Users/pranav/anaconda3/envs/myenv/lib/pyth

In [22]:
import matplotlib.pyplot as plt
import tensorflow as tf

In [23]:
number_list = []
for i in range(0, 10):
  number_list.append(os.path.join(directory_path, f'{i}'))

In [24]:
number_list

['/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/0',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/1',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/2',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/3',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/4',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/5',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/6',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/7',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/8',
 '/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/9']

In [25]:
# one = number_list[1]

In [26]:
# one

In [27]:
# one_train = tf.data.Dataset.list_files(one+'/*.wav')

In [28]:
# one_train = tf.data.Dataset.zip((one_train, tf.data.Dataset.from_tensor_slices(tf.ones(len(one_train)))))

In [29]:
# len(one_train)

In [30]:
dataset_list = []
for i in range(0, 10):
  dataset_list.append(tf.data.Dataset.list_files(number_list[i]+'/*.wav'))

In [31]:
dataset_list

[<_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>,
 <_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>]

In [32]:
# dataset = []
# for i in range(10):
#     dataset_i = dataset_list[i]
#     length_tensor = len(dataset_i)

#     def generator():
#         for item in dataset_i:
#             yield (item, length_tensor)

#     length_dataset = tf.data.Dataset.from_generator(generator, (tf.float32, tf.int32), (tf.TensorShape([]), tf.TensorShape([])))

#     dataset.append(length_dataset)

In [33]:
dataset = []
for i in range(0, 10):
    labels = tf.fill(dims=len(dataset_list[i]), value=i)
    dataset.append(tf.data.Dataset.zip(dataset_list[i], tf.data.Dataset.from_tensor_slices(labels)))

In [34]:
dataset

[<_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 <_ZipDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=()

In [35]:
data = None
for ds in dataset:
  if data is None:
    data = ds
  else:
    data = data.concatenate(ds)

In [36]:
data

<_ConcatenateDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [37]:
len(data)

30000

In [38]:
def load_wav_16k_mono(filename):
    file_contents = tf.io.read_file(filename)
    wav, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)
    wav = tf.squeeze(wav, axis=-1)
    sample_rate = tf.cast(sample_rate, dtype=tf.int64)
    # wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
    return wav

In [39]:
# file_contents = tf.io.read_file('/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/0/0_01_0.wav')

In [40]:
# wav, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)

In [41]:
# sample_rate = tf.cast(sample_rate, dtype=tf.int64)

In [42]:
# wav = tf.squeeze(wav, axis=-1)

In [43]:
# wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)

In [44]:
lengths = []
all_lengths = []
for i in range(0, 10):
    for files in os.listdir(os.path.join('/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/', str(i))):
        tensor_wave = load_wav_16k_mono(os.path.join(f'/Users/pranav/AIML/AI/CV/MyProjects/Detecting_NO_from_Audio/Detecting_phno_from_voice/{str(i)}', str(files)))
        lengths.append(len(tensor_wave))
    all_lengths.append(lengths)

In [45]:
len(all_lengths)

10

In [46]:
tf.math.reduce_mean(all_lengths)

<tf.Tensor: shape=(), dtype=int32, numpy=30844>

In [47]:
tf.math.reduce_min(all_lengths)

<tf.Tensor: shape=(), dtype=int32, numpy=14073>

In [48]:
tf.math.reduce_max(all_lengths)

<tf.Tensor: shape=(), dtype=int32, numpy=47998>

In [49]:
def preprocess(file_path, label):
    wav = load_wav_16k_mono(file_path)
    wav = wav[:30000]
    zero_padding = tf.zeros([30000] - tf.shape(wav), dtype=tf.float32)
    wav = tf.concat([zero_padding, wav],0)
    spectrogram = tf.signal.stft(wav, frame_length=80, frame_step=40)
    spectrogram = tf.abs(spectrogram)
    spectrogram = tf.expand_dims(spectrogram, axis=2)
    return spectrogram, label

In [50]:
def one_hot_encode(features, labels):
    labels_one_hot = tf.one_hot(labels, depth=10)
    return features, labels_one_hot

In [51]:
train_data = data.map(preprocess)
train_data = train_data.map(one_hot_encode)
train_data = train_data.cache()
train_data = train_data.shuffle(buffer_size=10000)
train_data = train_data.batch(8)
train_data = train_data.prefetch(4)

In [52]:
train_data

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, None, 65, 1), dtype=tf.float32, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))>

In [53]:
len(train_data)*.2

750.0

In [54]:
train = train_data.take(3000)
val = train_data.skip(3000).take(750)

In [55]:
train

<_TakeDataset element_spec=(TensorSpec(shape=(None, None, 65, 1), dtype=tf.float32, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))>

In [56]:
samples, labels = train.as_numpy_iterator().next()

2023-10-20 10:19:13.199939: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [57]:
samples.shape

(8, 749, 65, 1)

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten

In [59]:
model = Sequential()
model.add(Conv2D(16, (3,3), activation='relu', input_shape=(749, 65, 1)))
model.add(Conv2D(16, (3,3), activation='relu'))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [66]:
model.compile('Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [67]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 747, 63, 16)       160       
                                                                 
 conv2d_1 (Conv2D)           (None, 745, 61, 16)       2320      
                                                                 
 flatten (Flatten)           (None, 727120)            0         
                                                                 
 dense (Dense)               (None, 128)               93071488  
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 93075258 (355.05 MB)
Trainable params: 93075258 (355.05 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [69]:
hist = model.fit(train, epochs=2, validation_data=val)

Epoch 1/2
3000/3000 [==============================] - 763s 253ms/step - loss: 0.2470 - accuracy: 0.9339 - val_loss: 0.0807 - val_accuracy: 0.9797
Epoch 2/2
3000/3000 [==============================] - 715s 238ms/step - loss: 0.0860 - accuracy: 0.9747 - val_loss: 0.1464 - val_accuracy: 0.9533


In [70]:
model.save('audionodetect.h5')

/Users/pranav/anaconda3/envs/myenv/lib/python3.11/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
